#:import get_string locales.strings.get_string

<NavBar@BoxLayout>:
    size_hint_y: None
    height: dp(64)
    orientation: 'horizontal'
    canvas.before:
        Color:
            rgba: 0.09, 0.12, 0.2, 1
        Rectangle:
            pos: self.pos
            size: self.size

<NavButton@ButtonBehavior+BoxLayout>:
    orientation: 'vertical'
    label_text: ''
    active: False
    Label:
        text: root.label_text
        font_name: app.font_name
        color: (1, 0.85, 0.2, 1) if root.active else (0.7, 0.75, 0.85, 1)
        font_size: '13sp'
        bold: root.active
